"""Local independent market scanner and Telegram platform; Python 3.10+."""
import hashlib
from contextlib import contextmanager
import hmac
import html
import json
from datetime import datetime, timezone
from zoneinfo import ZoneInfo
import math
import os
from pathlib import Path
import re
import sqlite3
import signal
import ssl
import threading
import time
import urllib.error
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

ROOT = Path(os.environ.get('TRADING_BOT_ROOT',str(Path(__file__).resolve().parent)))
SKILL = ROOT / 'skills/rsi-divergence/SKILL.md'


def load_env():
    path = ROOT / '.env'
    if path.exists():
        for line in path.read_text().splitlines():
            if line.strip() and not line.lstrip().startswith('#'):
                # Ignore notes/headings pasted alongside credentials. Never log
                # arbitrary .env text: even a malformed line can contain a key.
                if '=' not in line:
                    continue
                key, value = line.split('=', 1)
                key = key.strip().removeprefix('export ').strip()
                if not re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]*', key):
                    continue
                value = value.strip()
                if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
                    value = value[1:-1]
                os.environ.setdefault(key, value)


def load_rules():
    text = SKILL.read_text()
    patterns = {
        'rsi_period': r'- RSI: (\d+) periods, Wilder smoothing, close prices\.',
        'bb_period': r'- Bollinger Bands: (\d+)-period',
        'bb_multiplier': r'plus/minus ([\d.]+) population standard deviations',
        'pivot_left': r'- Pivot confirmation: (\d+) candles to the left',
        'pivot_right': r'candles to the left and (\d+) to the right',
        'min_spacing': r'- Pivot spacing: (\d+)–\d+ candles',
        'max_spacing': r'- Pivot spacing: \d+–(\d+) candles',
        'band_slope_period': r'- Band-slope filter: measure the relevant outer band .* with a (\d+)-candle',
        'max_band_slope_pct': r'exceeds ([\d.]+)% per candle\.',
    }
    rules = {}
    for key, pattern in patterns.items():
        match = re.search(pattern, text)
        if not match:
            raise ValueError(f'Cannot read {key} from {SKILL}; update the parser explicitly.')
        rules[key] = float(match[1]) if key in ('bb_multiplier', 'max_band_slope_pct') else int(match[1])
    if any(v <= 0 for v in rules.values()) or rules['min_spacing'] > rules['max_spacing']:
        raise ValueError('Invalid indicator or pivot settings in skill.')
    source = re.search(r'- Divergence price source: (close)\.', text)
    if not source:
        raise ValueError('Missing close-based divergence price source in skill.')
    rules['price_source'] = source[1]
    rules['skill_hash'] = hashlib.sha256(text.encode()).hexdigest()[:16]
    return rules


def validate_signal(body, rules):
    """Recheck the evidence generated by the local engine or legacy webhook."""
    if body.get('rules') != rules:
        raise ValueError('Rules differ; restart the scanner with the current Markdown settings.')
    for key in ('symbol', 'timeframe'):
        if not isinstance(body.get(key), str) or not re.fullmatch(r'[A-Za-z0-9_:./!\-]{1,100}', body[key]):
            raise ValueError(f'Invalid {key}')
    if body.get('direction') not in ('bullish', 'bearish'):
        raise ValueError('Invalid direction')
    keys = ('price1', 'price2', 'rsi1', 'rsi2', 'band1', 'band2')
    for key in keys:
        v = body.get(key)
        if isinstance(v, bool) or not isinstance(v, (int, float)) or not math.isfinite(v):
            raise ValueError(f'Invalid {key}')
    for key in ('pivot1', 'pivot2', 'confirmed_at', 'spacing'):
        if type(body.get(key)) is not int or body[key] <= 0:
            raise ValueError(f'Invalid {key}')
    if not body['pivot1'] < body['pivot2'] < body['confirmed_at']:
        raise ValueError('Invalid pivot/confirmation ordering')
    if body['confirmed_at'] > int(time.time() * 1000) + 60_000:
        raise ValueError('Confirmation is in the future')
    if not all(0 <= body[k] <= 100 for k in ('rsi1', 'rsi2')):
        raise ValueError('RSI outside 0–100')
    if not rules['min_spacing'] <= body['spacing'] <= rules['max_spacing']:
        raise ValueError('Pivot spacing outside range')
    slope = body.get('band_slope_pct')
    if (isinstance(slope, bool) or not isinstance(slope, (int, float)) or not math.isfinite(slope)
            or abs(slope) > rules['max_band_slope_pct']):
        raise ValueError('Bollinger Band slope exceeds the configured limit')
    touch = body.get('band_touch_price', body['price2'])
    if isinstance(touch, bool) or not isinstance(touch, (int, float)) or not math.isfinite(touch):
        raise ValueError('Invalid band touch price')
    if (body['direction'] == 'bullish' and touch > body['price2']) or (body['direction'] == 'bearish' and touch < body['price2']):
        raise ValueError('Band touch inconsistent with pivot price')
    if body['direction'] == 'bullish':
        valid = body['price2'] < body['price1'] and body['rsi2'] > body['rsi1'] and touch <= body['band2']
    else:
        valid = body['price2'] > body['price1'] and body['rsi2'] < body['rsi1'] and touch >= body['band2']
    if not valid:
        raise ValueError('Divergence or band-touch rule failed')
    # Store only known fields; never persist the webhook authentication secret.
    clean = {k: body[k] for k in ('symbol', 'timeframe', 'direction', *keys, 'pivot1', 'pivot2', 'confirmed_at', 'spacing', 'rules', 'band_slope_pct')}
    if 'band_touch_price' in body:
        clean['band_touch_price'] = touch
    if any(k in body for k in ('signal_status', 'alert_timing', 'pivot_closed_at')):
        if (body.get('signal_status') != 'provisional' or body.get('alert_timing') != 'pivot_close'
                or type(body.get('pivot_closed_at')) is not int or body['pivot_closed_at'] != body['confirmed_at']):
            raise ValueError('Invalid provisional signal timing')
        clean.update(signal_status='provisional', alert_timing='pivot_close', pivot_closed_at=body['pivot_closed_at'])
    return clean


class Store:
    def __init__(self, path):
        self.path = path
        with self.connect() as db:
            db.execute('''CREATE TABLE IF NOT EXISTS signals (
                id TEXT PRIMARY KEY, payload TEXT NOT NULL, received REAL NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending', attempts INTEGER NOT NULL DEFAULT 0,
                next_attempt REAL NOT NULL DEFAULT 0, error TEXT)''')
            from finding_feedback import initialize
            initialize(db)
            from managed_assets import initialize as initialize_assets
            initialize_assets(db)
            from cloud_sync import initialize as initialize_sync
            initialize_sync(db)

    @contextmanager
    def connect(self):
        connection = sqlite3.connect(self.path, timeout=5)
        try:
            with connection:
                yield connection
        finally:
            connection.close()

    def insert(self, payload, delivery_status='pending',catchup_id=None):
        identity = [payload[k] for k in ('symbol', 'timeframe', 'direction', 'pivot1', 'pivot2')]
        if payload.get('signal_status') == 'provisional': identity.append('warmup')
        if payload.get('review_slot'): identity.append(payload['review_slot'])
        key = hashlib.sha256(json.dumps(identity).encode()).hexdigest()
        with self.connect() as db:
            result = db.execute('INSERT OR IGNORE INTO signals(id,payload,received,status) VALUES(?,?,?,?)',
                                (key, json.dumps(payload), time.time(),delivery_status))
            if result.rowcount==1 and catchup_id:
                db.execute('CREATE TABLE IF NOT EXISTS catchup_findings(command_id TEXT,signal_id TEXT,PRIMARY KEY(command_id,signal_id))')
                db.execute('INSERT OR IGNORE INTO catchup_findings VALUES(?,?)',(catchup_id,key))
            return result.rowcount == 1

    def log(self, event, details):
        with self.connect() as db:
            db.execute("CREATE TABLE IF NOT EXISTS activity_log(id INTEGER PRIMARY KEY, occurred REAL, event TEXT, details TEXT)")
            db.execute("INSERT INTO activity_log(occurred,event,details) VALUES(?,?,?)", (time.time(), event, details))

    def rows(self):
        with self.connect() as db:
            return db.execute('SELECT payload,status,attempts,error FROM signals ORDER BY received DESC LIMIT 100').fetchall()


def message(payload):
    provisional = payload.get('signal_status') == 'provisional'
    timestamp = payload['pivot_closed_at'] if provisional else payload['confirmed_at']
    stamp = datetime.fromtimestamp(timestamp / 1000, ZoneInfo('Asia/Jerusalem')).strftime('%d %b %Y at %H:%M (Israel time)')
    timing = f"Second pivot closed: {stamp}" if provisional else f"Confirmed: {stamp} ({payload['rules']['pivot_right']} following candle(s))"
    footer = 'Signal only · provisional pivot · closed candle' if provisional else 'Signal only · closed-candle divergence'
    return (f"{payload['direction'].upper()} RSI divergence{' (provisional)' if provisional else ''}\n"
            f"{payload['symbol']} · {payload['timeframe']}\n"
            f"Price: {payload['price1']:g} → {payload['price2']:g}\n"
            f"RSI({payload['rules']['rsi_period']}): {payload['rsi1']:.2f} → {payload['rsi2']:.2f}\n"
            f"{'Lower' if payload['direction'] == 'bullish' else 'Upper'} BB touch: {payload['band2']:g} · slope {payload['band_slope_pct']:+.2f}%/candle\n"
            f"{timing}\n{payload.get('stage_description', 'Warm-up / potential divergence; awaiting pivot confirmation.' if provisional else 'Confirmed divergence / structural pivot confirmation after the next candle.')}\n{footer}")


def telegram_connection_error(exc):
    reason = exc.reason if isinstance(exc, urllib.error.URLError) else exc
    if isinstance(reason, ssl.SSLCertVerificationError):
        return ('Telegram TLS certificate verification failed. Check the CA certificates '
                'for this Python interpreter, or use the configured project interpreter. '
                'Do not disable TLS verification.')
    if isinstance(reason, TimeoutError):
        return 'Telegram connection timed out. Check Internet/proxy access.'
    return 'Telegram connection failed. Check Internet/proxy access.'


def quiet_hours(now=None):
    local=datetime.fromtimestamp(time.time() if now is None else now,ZoneInfo('Asia/Jerusalem'))
    minute=local.hour*60+local.minute
    return minute>=23*60+30 or minute<6*60+30


def send_telegram(token, chat_id, text, silent=False):
    data = json.dumps({'chat_id': chat_id, 'text': text, 'disable_notification': silent}).encode()
    req = urllib.request.Request(f'https://api.telegram.org/bot{token}/sendMessage', data=data,
                                 headers={'Content-Type': 'application/json'})
    try:
        with urllib.request.urlopen(req, timeout=15) as response:
            result = json.load(response)
        if not result.get('ok'):
            raise RuntimeError('Telegram rejected message')
    except urllib.error.HTTPError as exc:
        # Do not log exception URLs: Telegram URLs contain the bot token.
        raise RuntimeError(f'Telegram HTTP {exc.code}') from None
    except (urllib.error.URLError, TimeoutError) as exc:
        raise RuntimeError(telegram_connection_error(exc)) from None


def delivery_worker(store, token, chat_id, dry_run, stop):
    from scanner_control import initialize as control_initialize
    with store.connect() as db:control_initialize(db)
    while not stop.is_set():
        with store.connect() as db:
            note=db.execute("SELECT id,text,attempts FROM notification_queue WHERE status='pending' AND next_attempt<=? ORDER BY rowid LIMIT 1",(time.time(),)).fetchone()
        if note:
            key,text,attempts=note
            try:
                if not dry_run:send_telegram(token,chat_id,text,silent=quiet_hours())
                with store.connect() as db:db.execute('UPDATE notification_queue SET status=? WHERE id=?',('dry-run' if dry_run else 'sent',key))
                store.log('Catch-up summary delivered','dry-run' if dry_run else 'sent')
            except Exception:
                with store.connect() as db:db.execute('UPDATE notification_queue SET attempts=?,next_attempt=? WHERE id=?',(attempts+1,time.time()+min(300,2**min(attempts+1,9)),key))
            continue
        with store.connect() as db:
            row = db.execute("SELECT id,payload,attempts FROM signals WHERE status='pending' AND next_attempt<=? ORDER BY received LIMIT 1", (time.time(),)).fetchone()
        if not row:
            stop.wait(1)
            continue
        key, raw, attempts = row
        if json.loads(raw).get('review_slot'):
            # Retire queued clock reviews from older versions without resending
            # cached setups after the move to candle-driven alerts.
            with store.connect() as db:
                db.execute("UPDATE signals SET status='cancelled',error=NULL WHERE id=?", (key,))
            continue
        store.log('Delivery attempt', f'{key} · attempt {attempts + 1}')
        try:
            if not dry_run:
                send_telegram(token, chat_id, message(json.loads(raw)))
            with store.connect() as db:
                db.execute('UPDATE signals SET status=?,attempts=?,error=NULL WHERE id=?',
                           ('dry-run' if dry_run else 'sent', attempts + 1, key))
            store.log('Delivery completed', 'dry-run' if dry_run else 'sent')
        except Exception as exc:
            # Persist a sanitized classification only, never arbitrary exception text.
            error = str(exc) if isinstance(exc, RuntimeError) else 'Delivery failed'
            store.log('Delivery failed', error)
            with store.connect() as db:
                db.execute('UPDATE signals SET attempts=?,next_attempt=?,error=? WHERE id=?',
                           (attempts + 1, time.time() + min(300, 2 ** min(attempts + 1, 9)), error, key))
        stop.wait(0.1)


def handler_factory(store, rules, secret, dry_run, dashboard=False):
    class Handler(BaseHTTPRequestHandler):
        def log_message(self, *args):
            pass

        def respond(self, status, body, content_type='application/json'):
            raw = body.encode() if isinstance(body, str) else json.dumps(body).encode()
            self.send_response(status)
            self.send_header('Content-Type', content_type)
            self.send_header('Content-Length', str(len(raw)))
            self.send_header('Cache-Control', 'no-store')
            self.send_header('X-Content-Type-Options', 'nosniff')
            self.end_headers()
            self.wfile.write(raw)

        def do_GET(self):
            if not dashboard:
                self.respond(404, {'error': 'Not found'})
                return
            # Never expose the dashboard/rules/health through the public tunnel.
            if self.headers.get('Host') not in ('localhost:8080', '127.0.0.1:8080', f'localhost:{self.server.server_port}', f'127.0.0.1:{self.server.server_port}'):
                self.respond(404, {'error': 'Not found'})
                return
            from urllib.parse import urlsplit
            route = urlsplit(self.path).path
            if route in ('/', '/signals', '/logs', '/backtest', '/assets', '/candle', '/dashboard'):
                self.respond(200, (ROOT / 'web/index.html').read_text(), 'text/html; charset=utf-8')
                return
            if route.startswith('/web/'):
                allowed_files = {'style.css':'text/css', 'app.js':'text/javascript', 'config.js':'text/javascript', 'chart.js':'text/javascript', 'vendor/lightweight-charts.js':'text/javascript', 'favicon.svg':'image/svg+xml'}
                name = route.removeprefix('/web/')
                if name in allowed_files:
                    self.respond(200, (ROOT / 'web' / name).read_text(), allowed_files[name])
                else:
                    self.respond(404, {'error':'Not found'})
                return
            if route in ('/api/assets', '/api/findings', '/api/candles', '/api/followup', '/api/logs', '/api/backtests','/api/catchup','/api/updates'):
                from dashboard_api import read
                try:
                    self.respond(200, read(store, self.path))
                except LookupError as exc:
                    self.respond(404, {'error':str(exc)})
                except (ValueError, TypeError):
                    self.respond(400, {'error':'Invalid dashboard request'})
                return
            if self.path == '/health':
                self.respond(200, {'ok': True, 'dry_run': dry_run, 'rules': rules})
            elif self.path == '/api/feedback/export':
                from finding_feedback import export
                self.respond(200, export(store))
            elif self.path in ('/signals', '/logs', '/backtest'):
                from dashboard_pages import render_page
                self.respond(200, render_page(store, self.path), 'text/html; charset=utf-8')
            elif self.path == '/':
                coverage = ''
                scan_note = 'Waiting for the first scan cycle.'
                with store.connect() as db:
                    exists = db.execute("SELECT name FROM sqlite_master WHERE name='scanner_status'").fetchone()
                    state = db.execute('SELECT payload FROM scanner_status WHERE id=1').fetchone() if exists else None
                if state:
                    scan_state = json.loads(state[0])
                    scanned_at = datetime.fromtimestamp(scan_state['scanned_at'] / 1000, timezone.utc).isoformat()
                    from managed_assets import effective
                    config, _ = effective(store, {})
                    poll_seconds = config.get('poll_seconds', 300)
                    scan_note = f'Latest cycle started: {scanned_at}. Polling at candle closes or within {poll_seconds // 60} minutes after each cycle. Reload to see updates.'
                    next_scan_at = scan_state.get('next_scan_at')
                    if scan_state.get('phase') == 'scanning':
                        next_scan = 'Scan cycle in progress'
                    elif next_scan_at and next_scan_at > time.time() * 1000:
                        next_scan = datetime.fromtimestamp(next_scan_at / 1000, ZoneInfo('Asia/Jerusalem')).strftime('%d %b %Y, %H:%M:%S %Z')
                    elif next_scan_at:
                        next_scan = 'Scheduled time passed — reload for status'
                    else:
                        next_scan = 'Awaiting scanner schedule'
                    scan_note += ' Next scan is the scheduled cycle start; rows are checked in sequence.'
                    for item in scan_state['coverage']:
                        last_close = datetime.fromtimestamp(item['last_closed_at'] / 1000, timezone.utc).isoformat() if item.get('last_closed_at') else ''
                        details = '; '.join(filter(None, [item.get('reason', ''), item.get('data_notes', ''), 'Limited history' if item.get('limited_history') else '']))
                        warning = item['status'] in ('unavailable', 'insufficient history') or item.get('provider') == 'csv'
                        if item.get('provider') == 'csv' and item['status'] != 'unavailable':
                            details = '; '.join(filter(None, [details, 'CSV data; live feed not connected']))
                        status_cell = html.escape(item['status'])
                        if warning:
                            status_cell = '<span class="data-warning" role="img" aria-label="Live data warning" title="' + html.escape(details or item['status'], quote=True) + '">⚠</span> ' + status_cell
                        values = (item.get('candles', ''), last_close, next_scan, details)
                        coverage += '<tr><td>' + html.escape(str(item['asset'])) + '</td><td>' + html.escape(str(item['timeframe'])) + '</td><td>' + status_cell + '</td>' + ''.join(f'<td>{html.escape(str(v))}</td>' for v in values) + '</tr>'
                self.respond(200, '''<!doctype html><html><head><meta charset="utf-8">
                <title>Divergence alerts</title><style>body{font:16px system-ui;background:#111827;color:#e5e7eb;margin:40px}a{color:#67e8f9}table{border-collapse:collapse;width:100%}td,th{padding:12px;text-align:left;border-bottom:1px solid #374151}code{color:#67e8f9}.data-warning{color:#facc15;font-size:20px;font-weight:bold}</style></head><body>
                <nav><a href="/">Overview</a> · <a href="/signals">Signals</a> · <a href="/logs">Logs</a> · <a href="/backtest">Backtest 2020</a> · <a href="/assets">Assets</a></nav><h1>Divergence alerts</h1><p>Market candles → local scanner → Telegram · signals only</p>'''
                + f'<p>RSI({rules["rsi_period"]}) close · BB({rules["bb_period"]}, {rules["bb_multiplier"]:g}) · Mode: {"dry run" if dry_run else "Telegram"}</p>'
                + '<h2>Scanner coverage</h2><p>' + html.escape(scan_note) + '</p><table><tr><th>Asset</th><th>Timeframe</th><th>Status</th><th>Closed candles</th><th>Last close (UTC)</th><th>Next scan (Israel time)</th><th>Details</th></tr>' + coverage + '</table></body></html>', 'text/html; charset=utf-8')
            else:
                self.respond(404, {'error': 'Not found'})

        def do_POST(self):
            if dashboard and self.path in ('/api/feedback', '/api/assets', '/api/backtests', '/api/finding-state','/api/catchup','/api/updates'):
                from finding_feedback import save
                host = self.headers.get('Host')
                allowed = (f'localhost:{self.server.server_port}', f'127.0.0.1:{self.server.server_port}')
                if (host not in allowed or self.headers.get('Origin') not in ('http://' + host,)
                        or self.headers.get('Content-Type') != 'application/json'):
                    self.respond(403, {'error': 'Feedback must be saved from the local dashboard'})
                    return
                try:
                    size = int(self.headers.get('Content-Length', '0'))
                    if not 0 < size <= 32768:
                        raise ValueError('Invalid body size')
                    self.connection.settimeout(2)
                    body = json.loads(self.rfile.read(size))
                    if not isinstance(body, dict):
                        raise ValueError('Expected JSON object')
                    if self.path=='/api/catchup':
                        from scanner_control import request
                        if body.get('action')!='request':raise ValueError('Invalid scanner action')
                        self.respond(202,request(store))
                    elif self.path=='/api/updates':
                        import windows_update
                        self.respond(202,windows_update.request_check())
                    elif self.path == '/api/finding-state':
                        from finding_state import change
                        self.respond(200, change(store, ROOT, body))
                    elif self.path == '/api/backtests':
                        from backtest_jobs import start
                        self.respond(202, start(store, body))
                    elif self.path == '/api/assets':
                        from dashboard_api import ensure
                        from managed_assets import change
                        ensure(store)
                        self.respond(200, change(store, body))
                    else:
                        self.respond(200, save(store, ROOT, body))
                except LookupError as exc:
                    self.respond(409, {'error': str(exc)})
                except (ValueError, TypeError, OSError):
                    self.respond(400, {'error': 'Invalid asset configuration or feedback'})
                except sqlite3.Error:
                    self.respond(503, {'error': 'Local storage unavailable. Try saving again.'})
                return
            if dashboard or self.path != '/webhook':
                self.respond(404, {'error': 'Not found'})
                return
            try:
                size = int(self.headers.get('Content-Length', '0'))
                if not 0 < size <= 16_384:
                    raise ValueError('Invalid body size')
                self.connection.settimeout(2)
                body = json.loads(self.rfile.read(size))
                if not isinstance(body, dict):
                    raise ValueError('Expected JSON object')
                supplied = body.get('secret')
                if not isinstance(supplied, str) or not hmac.compare_digest(supplied.encode(), secret.encode()):
                    self.respond(401, {'error': 'Unauthorized'})
                    return
                payload = validate_signal(body, rules)
                created = store.insert(payload)
                self.respond(202, {'accepted': True, 'duplicate': not created})
            except (ValueError, TypeError, KeyError, OSError):
                self.respond(400, {'error': 'Invalid signal, JSON, or rules version'})
    return Handler


class LocalHTTPServer(ThreadingHTTPServer):
    """Bounded request concurrency for small local machines."""
    def __init__(self, *args, **kwargs):
        self.request_slots = threading.BoundedSemaphore(8)
        super().__init__(*args, **kwargs)

    def process_request(self, request, client_address):
        if not self.request_slots.acquire(blocking=False):
            try:
                request.sendall(b'HTTP/1.1 503 Service Unavailable\r\nContent-Length: 0\r\nConnection: close\r\n\r\n')
            finally:
                self.shutdown_request(request)
            return
        try:
            super().process_request(request, client_address)
        except Exception:
            self.request_slots.release()
            raise

    def process_request_thread(self, request, client_address):
        try:
            super().process_request_thread(request, client_address)
        finally:
            self.request_slots.release()


def main():
    load_env()
    rules = load_rules()
    secret = os.environ.get('WEBHOOK_SECRET', '')
    token = os.environ.get('TELEGRAM_BOT_TOKEN', '')
    chat_id = os.environ.get('TELEGRAM_CHAT_ID', '')
    dry_run = os.environ.get('DRY_RUN', 'false').lower() == 'true'
    legacy_webhook = os.environ.get('MODE', 'scanner') == 'webhook'
    if legacy_webhook and len(secret) < 32:
        raise SystemExit('Set WEBHOOK_SECRET to a random value of at least 32 characters in .env.')
    if not dry_run and (not token or not chat_id):
        raise SystemExit('Set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID, or DRY_RUN=true.')
    data = Path(os.environ.get('DATA_DIR', str(ROOT / 'data')))
    data.mkdir(parents=True, exist_ok=True)
    store = Store(data / 'signals.sqlite3')
    if not legacy_webhook:
        from scanner import load_config
        from managed_assets import ensure
        from portfolio_upgrade import install
        ensure(store,load_config())
        install(store)
    store.log('Platform started', 'dry-run' if dry_run else 'Telegram')
    stop = threading.Event()
    worker = threading.Thread(target=delivery_worker, args=(store, token, chat_id, dry_run, stop), daemon=True)
    worker.start()
    from cloud_sync import worker as sync_worker
    sync_thread = threading.Thread(target=sync_worker, args=(store, stop), daemon=True)
    sync_thread.start()
    host = os.environ.get('HOST', '127.0.0.1')
    scanner_thread = None
    if not legacy_webhook:
        from scanner import load_config, scanner_worker, prepare_store
        config = load_config()
        prepare_store(store)
        scanner_thread = threading.Thread(target=scanner_worker, args=(store, config, rules, stop), daemon=True)
        scanner_thread.start()
    server = LocalHTTPServer((host, int(os.environ.get('PORT', '8080'))), handler_factory(store, rules, secret, dry_run, dashboard=True))
    from windows_update import worker as update_worker
    def update_shutdown():
        stop.set()
        server.shutdown()
    update_thread=threading.Thread(target=update_worker,args=(stop,update_shutdown),daemon=True)
    update_thread.start()
    webhook_server = None
    if legacy_webhook:
        webhook_server = ThreadingHTTPServer((host, int(os.environ.get('WEBHOOK_PORT', '8081'))), handler_factory(store, rules, secret, dry_run))
        threading.Thread(target=webhook_server.serve_forever, daemon=True).start()
    print(f'Dashboard port={server.server_port}; source={"legacy webhook" if legacy_webhook else "local scanner"}; delivery={"dry-run" if dry_run else "Telegram"}.')
    def terminate(signum, frame):
        raise KeyboardInterrupt
    signal.signal(signal.SIGTERM, terminate)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        stop.set()
        server.shutdown()
        server.server_close()
        if webhook_server:
            webhook_server.shutdown()
            webhook_server.server_close()
        stop.set()
        worker.join(timeout=20)
        sync_thread.join(timeout=12)
        if scanner_thread:
            scanner_thread.join(timeout=21)



if __name__ == '__main__':
    main()
