"""Local independent market scanner and Telegram platform; Python 3.10+."""
import hashlib
from contextlib import contextmanager
import hmac
import html
import json
from datetime import datetime, timezone
import math
import os
from pathlib import Path
import re
import sqlite3
import ssl
import threading
import time
import urllib.error
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

ROOT = Path(__file__).resolve().parent
SKILL = ROOT / 'skills/rsi-divergence/SKILL.md'


def load_env():
    path = ROOT / '.env'
    if path.exists():
        for line in path.read_text().splitlines():
            if line.strip() and not line.lstrip().startswith('#'):
                key, value = line.split('=', 1)
                os.environ.setdefault(key.strip(), value.strip())


def load_rules():
    text = SKILL.read_text()
    patterns = {
        'rsi_period': r'- RSI: (\d+) periods, Wilder smoothing, close prices\.',
        'bb_period': r'- Bollinger Bands: (\d+)-period',
        'bb_multiplier': r'plus/minus ([\d.]+) population standard deviations',
        'pivot_left': r'- Pivot confirmation: (\d+) candles to the left',
        'pivot_right': r'candles to the left and (\d+) to the right',
        'min_spacing': r'- Pivot spacing: (\d+)–\d+ candles',
        'max_spacing': r'- Pivot spacing: \d+–(\d+) candles',
    }
    rules = {}
    for key, pattern in patterns.items():
        match = re.search(pattern, text)
        if not match:
            raise ValueError(f'Cannot read {key} from {SKILL}; update the parser explicitly.')
        rules[key] = float(match[1]) if key == 'bb_multiplier' else int(match[1])
    if any(v <= 0 for v in rules.values()) or rules['min_spacing'] > rules['max_spacing']:
        raise ValueError('Invalid indicator or pivot settings in skill.')
    rules['skill_hash'] = hashlib.sha256(text.encode()).hexdigest()[:16]
    return rules


def validate_signal(body, rules):
    """Recheck the evidence generated by the local engine or legacy webhook."""
    if body.get('rules') != rules:
        raise ValueError('Rules differ; restart the scanner with the current Markdown settings.')
    for key in ('symbol', 'timeframe'):
        if not isinstance(body.get(key), str) or not re.fullmatch(r'[A-Za-z0-9_:./!\-]{1,100}', body[key]):
            raise ValueError(f'Invalid {key}')
    if body.get('direction') not in ('bullish', 'bearish'):
        raise ValueError('Invalid direction')
    keys = ('price1', 'price2', 'rsi1', 'rsi2', 'band1', 'band2')
    for key in keys:
        v = body.get(key)
        if isinstance(v, bool) or not isinstance(v, (int, float)) or not math.isfinite(v):
            raise ValueError(f'Invalid {key}')
    for key in ('pivot1', 'pivot2', 'confirmed_at', 'spacing'):
        if type(body.get(key)) is not int or body[key] <= 0:
            raise ValueError(f'Invalid {key}')
    if not body['pivot1'] < body['pivot2'] < body['confirmed_at']:
        raise ValueError('Invalid pivot/confirmation ordering')
    if body['confirmed_at'] > int(time.time() * 1000) + 60_000:
        raise ValueError('Confirmation is in the future')
    if not all(0 <= body[k] <= 100 for k in ('rsi1', 'rsi2')):
        raise ValueError('RSI outside 0–100')
    if not rules['min_spacing'] <= body['spacing'] <= rules['max_spacing']:
        raise ValueError('Pivot spacing outside range')
    if body['direction'] == 'bullish':
        valid = body['price2'] < body['price1'] and body['rsi2'] > body['rsi1'] and body['price2'] <= body['band2']
    else:
        valid = body['price2'] > body['price1'] and body['rsi2'] < body['rsi1'] and body['price2'] >= body['band2']
    if not valid:
        raise ValueError('Divergence or band-touch rule failed')
    # Store only known fields; never persist the webhook authentication secret.
    return {k: body[k] for k in ('symbol', 'timeframe', 'direction', *keys, 'pivot1', 'pivot2', 'confirmed_at', 'spacing', 'rules')}


class Store:
    def __init__(self, path):
        self.path = path
        with self.connect() as db:
            db.execute('''CREATE TABLE IF NOT EXISTS signals (
                id TEXT PRIMARY KEY, payload TEXT NOT NULL, received REAL NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending', attempts INTEGER NOT NULL DEFAULT 0,
                next_attempt REAL NOT NULL DEFAULT 0, error TEXT)''')

    @contextmanager
    def connect(self):
        connection = sqlite3.connect(self.path, timeout=5)
        try:
            with connection:
                yield connection
        finally:
            connection.close()

    def insert(self, payload):
        identity = [payload[k] for k in ('symbol', 'timeframe', 'direction', 'pivot1', 'pivot2')]
        key = hashlib.sha256(json.dumps(identity).encode()).hexdigest()
        with self.connect() as db:
            result = db.execute('INSERT OR IGNORE INTO signals(id,payload,received) VALUES(?,?,?)',
                                (key, json.dumps(payload), time.time()))
            return result.rowcount == 1

    def log(self, event, details):
        with self.connect() as db:
            db.execute("CREATE TABLE IF NOT EXISTS activity_log(id INTEGER PRIMARY KEY, occurred REAL, event TEXT, details TEXT)")
            db.execute("INSERT INTO activity_log(occurred,event,details) VALUES(?,?,?)", (time.time(), event, details))

    def rows(self):
        with self.connect() as db:
            return db.execute('SELECT payload,status,attempts,error FROM signals ORDER BY received DESC LIMIT 100').fetchall()


def message(payload):
    from datetime import datetime, timezone
    stamp = datetime.fromtimestamp(payload['confirmed_at'] / 1000, timezone.utc).isoformat()
    return (f"{payload['direction'].upper()} RSI divergence\n"
            f"{payload['symbol']} · {payload['timeframe']}\n"
            f"Price: {payload['price1']:g} → {payload['price2']:g}\n"
            f"RSI({payload['rules']['rsi_period']}): {payload['rsi1']:.2f} → {payload['rsi2']:.2f}\n"
            f"{'Lower' if payload['direction'] == 'bullish' else 'Upper'} BB touch: {payload['band2']:g}\n"
            f"Confirmed: {stamp}\nSignal only · closed-candle divergence")


def telegram_connection_error(exc):
    reason = exc.reason if isinstance(exc, urllib.error.URLError) else exc
    if isinstance(reason, ssl.SSLCertVerificationError):
        return ('Telegram TLS certificate verification failed. Check the CA certificates '
                'for this Python interpreter, or use the configured project interpreter. '
                'Do not disable TLS verification.')
    if isinstance(reason, TimeoutError):
        return 'Telegram connection timed out. Check Internet/proxy access.'
    return 'Telegram connection failed. Check Internet/proxy access.'


def send_telegram(token, chat_id, text):
    data = json.dumps({'chat_id': chat_id, 'text': text}).encode()
    req = urllib.request.Request(f'https://api.telegram.org/bot{token}/sendMessage', data=data,
                                 headers={'Content-Type': 'application/json'})
    try:
        with urllib.request.urlopen(req, timeout=15) as response:
            result = json.load(response)
        if not result.get('ok'):
            raise RuntimeError('Telegram rejected message')
    except urllib.error.HTTPError as exc:
        # Do not log exception URLs: Telegram URLs contain the bot token.
        raise RuntimeError(f'Telegram HTTP {exc.code}') from None
    except (urllib.error.URLError, TimeoutError) as exc:
        raise RuntimeError(telegram_connection_error(exc)) from None


def delivery_worker(store, token, chat_id, dry_run, stop):
    while not stop.is_set():
        with store.connect() as db:
            row = db.execute("SELECT id,payload,attempts FROM signals WHERE status='pending' AND next_attempt<=? ORDER BY received LIMIT 1", (time.time(),)).fetchone()
        if not row:
            stop.wait(1)
            continue
        key, raw, attempts = row
        store.log('Delivery attempt', f'{key} · attempt {attempts + 1}')
        try:
            if not dry_run:
                send_telegram(token, chat_id, message(json.loads(raw)))
            with store.connect() as db:
                db.execute('UPDATE signals SET status=?,attempts=?,error=NULL WHERE id=?',
                           ('dry-run' if dry_run else 'sent', attempts + 1, key))
            store.log('Delivery completed', 'dry-run' if dry_run else 'sent')
        except Exception as exc:
            # Persist a sanitized classification only, never arbitrary exception text.
            error = str(exc) if isinstance(exc, RuntimeError) else 'Delivery failed'
            store.log('Delivery failed', error)
            with store.connect() as db:
                db.execute('UPDATE signals SET attempts=?,next_attempt=?,error=? WHERE id=?',
                           (attempts + 1, time.time() + min(300, 2 ** min(attempts + 1, 9)), error, key))
        stop.wait(0.1)


def handler_factory(store, rules, secret, dry_run, dashboard=False):
    class Handler(BaseHTTPRequestHandler):
        def log_message(self, *args):
            pass

        def respond(self, status, body, content_type='application/json'):
            raw = body.encode() if isinstance(body, str) else json.dumps(body).encode()
            self.send_response(status)
            self.send_header('Content-Type', content_type)
            self.send_header('Content-Length', str(len(raw)))
            self.send_header('Cache-Control', 'no-store')
            self.send_header('X-Content-Type-Options', 'nosniff')
            self.end_headers()
            self.wfile.write(raw)

        def do_GET(self):
            if not dashboard:
                self.respond(404, {'error': 'Not found'})
                return
            # Never expose the dashboard/rules/health through the public tunnel.
            if self.headers.get('Host') not in ('localhost:8080', '127.0.0.1:8080', f'localhost:{self.server.server_port}', f'127.0.0.1:{self.server.server_port}'):
                self.respond(404, {'error': 'Not found'})
                return
            if self.path == '/health':
                self.respond(200, {'ok': True, 'dry_run': dry_run, 'rules': rules})
            elif self.path in ('/logs', '/backtest'):
                from dashboard_pages import render_page
                self.respond(200, render_page(store, self.path), 'text/html; charset=utf-8')
            elif self.path == '/':
                coverage = ''
                with store.connect() as db:
                    exists = db.execute("SELECT name FROM sqlite_master WHERE name='scanner_status'").fetchone()
                    state = db.execute('SELECT payload FROM scanner_status WHERE id=1').fetchone() if exists else None
                if state:
                    for item in json.loads(state[0])['coverage']:
                        last_close = datetime.fromtimestamp(item['last_closed_at'] / 1000, timezone.utc).isoformat() if item.get('last_closed_at') else ''
                        details = item.get('reason', '') or ('Limited history' if item.get('limited_history') else '')
                        values = (item['asset'], item['timeframe'], item['status'], item.get('candles', ''), last_close, details)
                        coverage += '<tr>' + ''.join(f'<td>{html.escape(str(v))}</td>' for v in values) + '</tr>'
                rows = ''
                for raw, status, attempts, error in store.rows():
                    p = json.loads(raw)
                    values = (p['symbol'], p['timeframe'], p['direction'], f"{p['price1']:g} → {p['price2']:g}",
                              f"{p['rsi1']:.2f} → {p['rsi2']:.2f}", status, attempts, error or '')
                    rows += '<tr>' + ''.join(f'<td>{html.escape(str(v))}</td>' for v in values) + '</tr>'
                self.respond(200, '''<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="refresh" content="10">
                <title>Divergence alerts</title><style>body{font:16px system-ui;background:#111827;color:#e5e7eb;margin:40px}table{border-collapse:collapse;width:100%}td,th{padding:12px;text-align:left;border-bottom:1px solid #374151}code{color:#67e8f9}</style></head><body>
                <nav><a href="/">Overview</a> · <a href="/logs">Logs</a> · <a href="/backtest">Backtest 2020</a></nav><h1>Divergence alerts</h1><p>Market candles → local scanner → Telegram · signals only</p>'''
                + f'<p>RSI({rules["rsi_period"]}) close · BB({rules["bb_period"]}, {rules["bb_multiplier"]:g}) · Mode: {"dry run" if dry_run else "Telegram"}</p>'
                + '<h2>Scanner coverage</h2><table><tr><th>Asset</th><th>Timeframe</th><th>Status</th><th>Closed candles</th><th>Last close (UTC)</th><th>Details</th></tr>' + coverage + '</table><h2>Signals</h2>'
                + '<table><tr><th>Asset</th><th>Timeframe</th><th>Signal</th><th>Price pivots</th><th>RSI pivots</th><th>Delivery</th><th>Attempts</th><th>Error</th></tr>'
                + rows + '</table><p>Last 100 received signals. No rows means no signals received; it does not establish market coverage.</p></body></html>', 'text/html; charset=utf-8')
            else:
                self.respond(404, {'error': 'Not found'})

        def do_POST(self):
            if dashboard or self.path != '/webhook':
                self.respond(404, {'error': 'Not found'})
                return
            try:
                size = int(self.headers.get('Content-Length', '0'))
                if not 0 < size <= 16_384:
                    raise ValueError('Invalid body size')
                self.connection.settimeout(2)
                body = json.loads(self.rfile.read(size))
                if not isinstance(body, dict):
                    raise ValueError('Expected JSON object')
                supplied = body.get('secret')
                if not isinstance(supplied, str) or not hmac.compare_digest(supplied.encode(), secret.encode()):
                    self.respond(401, {'error': 'Unauthorized'})
                    return
                payload = validate_signal(body, rules)
                created = store.insert(payload)
                self.respond(202, {'accepted': True, 'duplicate': not created})
            except (ValueError, TypeError, KeyError, OSError):
                self.respond(400, {'error': 'Invalid signal, JSON, or rules version'})
    return Handler


def main():
    load_env()
    rules = load_rules()
    secret = os.environ.get('WEBHOOK_SECRET', '')
    token = os.environ.get('TELEGRAM_BOT_TOKEN', '')
    chat_id = os.environ.get('TELEGRAM_CHAT_ID', '')
    dry_run = os.environ.get('DRY_RUN', 'false').lower() == 'true'
    legacy_webhook = os.environ.get('MODE', 'scanner') == 'webhook'
    if legacy_webhook and len(secret) < 32:
        raise SystemExit('Set WEBHOOK_SECRET to a random value of at least 32 characters in .env.')
    if not dry_run and (not token or not chat_id):
        raise SystemExit('Set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID, or DRY_RUN=true.')
    data = Path(os.environ.get('DATA_DIR', str(ROOT / 'data')))
    data.mkdir(parents=True, exist_ok=True)
    store = Store(data / 'signals.sqlite3')
    store.log('Platform started', 'dry-run' if dry_run else 'Telegram')
    stop = threading.Event()
    worker = threading.Thread(target=delivery_worker, args=(store, token, chat_id, dry_run, stop), daemon=True)
    worker.start()
    host = os.environ.get('HOST', '127.0.0.1')
    scanner_thread = None
    if not legacy_webhook:
        from scanner import load_config, scanner_worker, prepare_store
        config = load_config()
        prepare_store(store)
        scanner_thread = threading.Thread(target=scanner_worker, args=(store, config, rules, stop), daemon=True)
        scanner_thread.start()
    server = ThreadingHTTPServer((host, int(os.environ.get('PORT', '8080'))), handler_factory(store, rules, secret, dry_run, dashboard=True))
    webhook_server = None
    if legacy_webhook:
        webhook_server = ThreadingHTTPServer((host, int(os.environ.get('WEBHOOK_PORT', '8081'))), handler_factory(store, rules, secret, dry_run))
        threading.Thread(target=webhook_server.serve_forever, daemon=True).start()
    print(f'Dashboard port={server.server_port}; source={"legacy webhook" if legacy_webhook else "local scanner"}; delivery={"dry-run" if dry_run else "Telegram"}.')
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.shutdown()
        server.server_close()
        if webhook_server:
            webhook_server.shutdown()
            webhook_server.server_close()
        stop.set()
        worker.join(timeout=20)
        if scanner_thread:
            scanner_thread.join(timeout=21)



if __name__ == '__main__':
    main()
