const config=window.DASHBOARD_CONFIG||{}, online=Boolean(config.supabaseUrl);
const $=id=>document.getElementById(id),content=$('content'),status=$('status');
const frames=['monthly','weekly','daily','4h','1h'];
const selectedFindings={live:sessionStorage.getItem('selected_live'),backtest:sessionStorage.getItem('selected_backtest')};
function selectFinding(source,id){selectedFindings[source]=id;sessionStorage.setItem?.('selected_'+source,id);for(const tr of document.querySelectorAll?.('.finding-row')||[]){const active=tr.dataset.findingId===id;tr.classList.toggle('selected-row',active);tr.setAttribute('aria-selected',String(active));}}
function marketCategory(a){if(a.market==='crypto')return 'Crypto';if(a.market==='forex')return 'Forex';if(a.market==='futures')return 'Futures';if(['stock','etf','equity'].includes(a.market)||['NASDAQ','NYSE','AMEX','NYSE ARCA'].includes(a.exchange))return 'Stocks & ETFs';return 'Other assets';}
function coverageWarning(a){const rows=(state.coverage||[]).filter(r=>r.asset===a.id);return rows.filter(r=>/unavailable|insufficient|partial/.test(r.status)).map(r=>r.timeframe+': '+(r.reason||r.status)).join('; ')||a.unavailable_reason||(a.provider==='csv'?'Live feed not connected':'');}
function outcomeCell(r){const n=node('div');r.outcomeElement=n;updateOutcome(r);return n;}
function updateOutcome(r){if(!r.outcomeElement)return;const f=r.followup;r.outcomeElement.replaceChildren();if(!f||f.status==='unavailable'){r.outcomeElement.append(node('small',f?.reason||'Awaiting follow-up'));return;}const gain=node('strong',`Gain ${f.gain_pct.toFixed(2)}%`),dd=node('strong',`Drawdown ${f.drawdown_pct.toFixed(2)}%`);gain.className='success';dd.className='error';r.outcomeElement.append(gain,dd,node('small',f.mode==='all'?'All available history':'Through first recovery'));}
let state,token=sessionStorage.getItem('dashboard_token'),chart=null;
const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
function message(text,error=false){status.textContent=text;status.className=error?'error':'';}
let passwordSetupSession=null;
if(online&&location.hash){
 const auth=new URLSearchParams(location.hash.slice(1));
 const code=auth.get('error_code'),description=auth.get('error_description');
 if(code){
  message(code==='otp_expired'?'This sign-in link has expired or was already used. Request a new link below.':(description||'The sign-in link could not be verified.'),true);
  history.replaceState(null,'',location.pathname+location.search);
 }else if(auth.get('access_token')&&auth.get('refresh_token')){
  const session={access_token:auth.get('access_token'),refresh_token:auth.get('refresh_token'),expires_in:Number(auth.get('expires_in'))||3600};
  const type=auth.get('type');
  if(['invite','recovery','signup'].includes(type)){
   passwordSetupSession=session;
   $('invite-setup').hidden=false;
   $('login').hidden=true;
  }else if(['magiclink','email'].includes(type)){
   saveSession(session);
   $('login').hidden=true;
  }
  history.replaceState(null,'',location.pathname+location.search);
 }
}
async function request(path,body){
 if(online)await refreshSession();
 let url=path,headers={},method=body?'POST':'GET';
 if(online){url=config.supabaseUrl+'/rest/v1/rpc/dashboard_api';method='POST';headers={apikey:config.publishableKey,Authorization:'Bearer '+token};body={installation:config.installationId,operation:path,input:body||{}};}
 if(online&&path==='/api/backtests'&&body.input&&Object.keys(body.input).length){url=config.supabaseUrl+'/functions/v1/backtests';body={installation:config.installationId,input:body.input};}
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);
 try{const r=await fetch(url,{method,headers:{...headers,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:controller.signal});const result=await r.json();if(online&&r.status===401){sessionStorage.removeItem('dashboard_token');token=null;$('login').hidden=false;}if(!r.ok||result.error)throw Error(result.error||result.message||'Request failed');return result;}finally{clearTimeout(timer);}
}
let refreshPending=null;
function saveSession(data){token=data.access_token;sessionStorage.setItem('dashboard_token',token);sessionStorage.setItem('dashboard_refresh',data.refresh_token);sessionStorage.setItem('dashboard_expires',String(data.expires_at||Math.floor(Date.now()/1000)+data.expires_in));}
async function refreshSession(){const refresh=sessionStorage.getItem('dashboard_refresh'),expires=Number(sessionStorage.getItem('dashboard_expires'));if(!refresh||expires>Date.now()/1000+60)return;if(refreshPending)return refreshPending;refreshPending=(async()=>{const r=await fetch(config.supabaseUrl+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:refresh})});const data=await r.json();if(!r.ok){for(const key of ['dashboard_token','dashboard_refresh','dashboard_expires'])sessionStorage.removeItem(key);token=null;throw Error('Session expired. Please sign in again.');}saveSession(data);})();try{await refreshPending;}finally{refreshPending=null;}}
$('signin').onclick=async()=>{try{const r=await fetch(config.supabaseUrl+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})});const data=await r.json();if(!r.ok)throw Error(data.msg||data.message||'Sign in failed');saveSession(data);$('password').value='';$('login').hidden=true;await load();}catch(e){message(e.message,true);}};
async function sendAuthLink(kind){try{const email=$('email').value.trim();if(!email){$('email').focus();throw Error('Enter your email address first.');}const redirect=encodeURIComponent(location.origin+'/'),recovery=kind==='recovery',path=recovery?'/auth/v1/recover?redirect_to='+redirect:'/auth/v1/otp?redirect_to='+redirect,body=recovery?{email}:{email,create_user:false};const r=await fetch(config.supabaseUrl+path,{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await r.json().catch(()=>({}));if(r.status===429)throw Error('Too many authentication emails were requested. Please wait before requesting another link.');if(!r.ok)throw Error(data.msg||data.message||data.error_description||'Could not send the email. Try again in a minute.');message(recovery?'If an account exists for that email, a password reset link is on its way.':'If an account exists for that email, a sign-in link is on its way.');}catch(e){message(e.message,true);}}
$('forgot-password').onclick=()=>sendAuthLink('recovery');
$('magic-link').onclick=()=>sendAuthLink('magiclink');
$('accept-invite').onclick=async()=>{try{if(!passwordSetupSession)throw Error('This password link is no longer active. Request a new one below.');const password=$('invite-password').value,confirm=$('invite-password-confirm').value;if(password.length<8)throw Error('Choose a password with at least 8 characters.');if(password!==confirm)throw Error('The passwords do not match.');const r=await fetch(config.supabaseUrl+'/auth/v1/user',{method:'PUT',headers:{apikey:config.publishableKey,Authorization:'Bearer '+passwordSetupSession.access_token,'Content-Type':'application/json'},body:JSON.stringify({password})});const data=await r.json();if(!r.ok)throw Error(data.msg||data.message||'Could not set the password. Request a new password link and try again.');saveSession(passwordSetupSession);passwordSetupSession=null;$('invite-password').value='';$('invite-password-confirm').value='';$('invite-setup').hidden=true;await load();}catch(e){message(e.message,true);}};
function button(text,fn){const b=node('button',text);b.type='button';b.onclick=fn;return b;}
async function loadAssets(){state=await request('/api/assets');content.replaceChildren();
 content.append(node('h2','Live assets'),node('p',`Configuration ${state.revision}; scanner applied ${state.applied_revision}. New tickers are disabled drafts until you configure their data feed.`));
 const form=node('form'),input=node('input');input.name='tickers';input.placeholder='NVDA, EURUSD, BTCUSD';input.required=true;input.maxLength=10000;form.append(input,node('button','Add tickers'));form.onsubmit=async e=>{e.preventDefault();await mutate({action:'bulk',tickers:input.value});};if(state.sync?.error)content.append(node('p','Sync: '+state.sync.error));
 if(!online&&state.configuration_conflict)content.append(button('Use online configuration',()=>mutate({action:'accept_online'})));
 if(!online&&state.conflicts)content.append(node('p',`${state.conflicts} sync conflicts retained for review. Pending local edits are preserved.`));
 content.append(form,node('p',`Candle timeframes are independent per asset. Polling interval: ${state.config.poll_seconds/3600} hours.`));
 if(state.config.daily_universe?.enabled){
  content.append(node('h3','Morning selection'),node('p','Five extra forex and five extra crypto pairs at 08:00 Israel time, held until the next morning. Ranked by Kraken 24-hour volume in USD; forex can use verified OANDA feeds, crypto native candles use Kraken, and monthly crypto stays on Twelve Data.'));
  const daily=state.daily_selection;
  if(daily){content.append(node('p',`${daily.session}: ${daily.status}. ${daily.reason||''}`));for(const market of ['forex','crypto'])content.append(selectionTable([market,'24h volume (USD)'],daily.selected[market].map(r=>[r.symbol,Math.round(r.volume_usd).toLocaleString()]),daily.selected[market].map(r=>r.symbol.replaceAll('/',''))));}
  else content.append(node('p','Daily selection will appear after the local worker refreshes it.'));
 }
 if(state.config.weekly_stock_screen?.enabled){
  const stocks=state.weekly_stock_selection;
  content.append(node('h3','Daily weekly-candle stock screen'),node('p','Ten S&P 400/500 stocks touching the upper Bollinger Band and ten touching the lower band in the last five completed weekly candles are selected at 08:00 Israel time. Picks stay unique on weekdays within each calendar week; the same stock can return next week. Only actual band touches qualify.'));
  if(stocks){content.append(node('p',`${stocks.day} · week of ${stocks.week} · ${stocks.status}${stocks.reason?' · '+stocks.reason:''}`));for(const side of ['upper','lower'])content.append(selectionTable([side==='upper'?'Upper BB':'Lower BB','Ticker','Distance from band (%)'],(stocks.selected?.[side]||[]).map(row=>[side,row.symbol,row.distance_pct.toFixed(3)]),(stocks.selected?.[side]||[]).map(row=>'STOCK-'+row.symbol)));}
  else content.append(node('p','The weekly stock screen will appear after the local worker refreshes it.'));
 }
 content.append(node('h3','Permanent portfolio'));
 const groups=new Map();for(const a of state.config.assets){const category=marketCategory(a);if(!groups.has(category)){const section=node('section');section.className='asset-group';section.append(node('h4',category));groups.set(category,section);}}for(const category of ['Stocks & ETFs','Forex','Futures','Crypto','Other assets'])if(groups.has(category))content.append(groups.get(category));
 for(const asset of state.config.assets){const warning=coverageWarning(asset),row=node('details'),summary=node('summary',`${asset.id}${asset.name?' · '+asset.name:''} · ${asset.enabled?'Enabled':'Disabled'} · ${(asset.timeframes||frames.filter(f=>f!=='1h')).join(', ')}${warning?' · Data unavailable':''}`);row.className='asset-row'+(warning?' asset-unavailable':'');row.append(summary);summary.title=warning;row.ontoggle=()=>row.classList.toggle('selected-row',row.open);const field=node('fieldset');if(warning){const note=node('p',warning);note.className='error';field.append(note);}
 const enabled=node('input');enabled.type='checkbox';enabled.checked=asset.enabled;const enablelabel=node('label','Scan enabled');enablelabel.append(enabled);field.append(enablelabel);
 const provider=node('select');for(const p of ['csv','twelvedata','kraken','oanda','tiingo','alpaca']){const o=node('option',p==='csv'?'Candle CSV files':p==='kraken'?'Kraken spot':p==='oanda'?'OANDA forex':p==='tiingo'?'Tiingo forex':p==='alpaca'?'Alpaca US equities':'Twelve Data');o.value=p;provider.append(o);}provider.value=asset.provider;field.append(provider);
 const inputs={};for(const [key,title] of [['symbol','Provider symbol'],['exchange','Provider exchange'],['tradingview_symbol','TradingView exchange:ticker']]){const l=node('label',title),i=node('input');i.value=asset[key]||'';i.maxLength=100;inputs[key]=i;l.append(i);field.append(l);}
 const confirmed=node('input');confirmed.type='checkbox';confirmed.checked=asset.feed_confirmed===true;const cl=node('label','I verified this provider feed');cl.append(confirmed);field.append(cl);
 const selected={},sources={};for(const f of frames){const l=node('label',f),i=node('input');i.type='checkbox';i.checked=(asset.timeframes||frames.filter(f=>f!=='1h')).includes(f);selected[f]=i;l.append(i);field.append(l);const source=node('select');source.setAttribute('aria-label',f+' candle provider');for(const [value,label] of [['','Primary provider'],['twelvedata','Twelve Data'],['oanda','OANDA forex'],['tiingo','Tiingo forex'],['alpaca','Alpaca US equities'],...(f==='monthly'?[]:[['kraken','Kraken spot']])]){const o=node('option',label);o.value=value;source.append(o);}source.value=asset.timeframe_providers?.[f]||'';sources[f]=source;field.append(source);}
 field.append(node('p',asset.provider==='csv'?`CSV: ${asset.path||'data/candles/{asset}-{timeframe}.csv'}`:'Provider entitlement and native intervals must be verified.'));
 field.append(node('p','OANDA supports forex on all five timeframes; its token and account ID stay in the local .env. Kraken supports crypto 1h, 4h, daily and weekly; monthly crypto stays on Twelve Data. Changing the venue starts a new alert baseline. Hourly is optional.'));
 field.append(button('Save asset',()=>mutate({action:'save',asset:{id:asset.id,provider:provider.value,enabled:enabled.checked,timeframes:frames.filter(f=>selected[f].checked),feed_confirmed:confirmed.checked,timeframe_providers:Object.fromEntries(frames.filter(f=>sources[f].value).map(f=>[f,sources[f].value])),...Object.fromEntries(Object.entries(inputs).map(([k,v])=>[k,v.value.trim()]))}})),button('Disable',()=>mutate({action:'save',asset:{...asset,enabled:false}})),button('Remove asset',()=>mutate({action:'remove',ticker:asset.id})));row.append(field);groups.get(marketCategory(asset)).append(row);
 }
}
async function mutate(body){try{message('Saving…');const result=await request('/api/assets',{...body,revision:state.revision});await loadAssets();message(result.results.map(r=>r.ticker+': '+r.status).join('; ')+(online?' — pending local scanner':' — saved locally'));}catch(e){message(e.message,true);}}
function displayTime(ms){return new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Jerusalem',dateStyle:'medium',timeStyle:'short'}).format(new Date(ms));}
function table(headers,rows){const t=node('table'),head=node('tr');for(const h of headers){const th=node('th');th.append(h instanceof Node?h:node('span',h));if(h instanceof Node&&h.dataset.sortState)th.setAttribute('aria-sort',h.dataset.sortState);head.append(th);}t.append(head);for(const row of rows){const tr=node('tr');for(const value of row){const td=node('td');td.append(value instanceof Node?value:node('span',String(value??'')));tr.append(td);}t.append(tr);}const wrap=node('div');wrap.className='scroll';wrap.append(t);return wrap;}
function selectionTable(headers,rows,ids){const grid=table(headers,rows);for(const [index,tr] of [...grid.querySelectorAll('tr')].slice(1).entries()){const coverage=(state.coverage||[]).filter(r=>r.asset===ids[index]),warning=coverage.filter(r=>/unavailable|insufficient|partial/.test(r.status));if(warning.length)tr.classList.add('error');tr.classList.add('finding-row');tr.tabIndex=0;tr.setAttribute('aria-expanded','false');tr.title='Click for feed and candle coverage';let detail;const toggle=()=>{if(!detail){detail=node('tr');const td=node('td');td.colSpan=headers.length;td.textContent=coverage.length?coverage.map(r=>`${r.timeframe} · ${r.provider} · ${r.status}${r.last_closed_at?' · latest close '+displayTime(r.last_closed_at):''}${r.next_close_at?' · next check '+displayTime(r.next_close_at):''}${r.reason?' · '+r.reason:''}`).join(' | '):'Awaiting the scanner’s first coverage check for this selection.';detail.append(td);tr.after(detail);}else detail.hidden=!detail.hidden;tr.classList.toggle('selected-row',!detail.hidden);tr.setAttribute('aria-expanded',String(!detail.hidden));};tr.onclick=toggle;tr.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle();}};}return grid;}
let page=0,showArchived=false;
const backtestSort={key:'confirmed_at',order:'asc'};
const strategyViews={live:'rsi',backtest:'rsi'};
function strategySelector(source){const label=node('label','Strategy '),select=node('select');select.setAttribute('aria-label','Strategy view');for(const [key,name] of [['rsi','RSI divergence'],['momentum','Daily momentum']]){const option=node('option',name);option.value=key;select.append(option);}select.value=strategyViews[source];select.onchange=()=>{strategyViews[source]=select.value;page=0;findings(source).catch(e=>message(e.message,true));};label.append(select);return label;}
async function findings(source){
 if(strategyViews[source]==='momentum')return momentumFindings(source);
 const result=await request(`/api/findings?source=${source}&page=${page}&archived=${showArchived}${source==='backtest'?`&sort=${backtestSort.key}&order=${backtestSort.order}`:''}`);if(strategyViews[source]!=='rsi')return;content.replaceChildren(node('h2',source==='live'?'Signal workspace':'Historical research'));
 content.append(strategySelector(source));
 if(source==='live'){const label=node('label','Show archived'),check=node('input');check.type='checkbox';check.checked=showArchived;check.onchange=()=>{showArchived=check.checked;page=0;findings(source).catch(e=>message(e.message,true));};label.prepend(check);content.append(label);}
 const metrics=node('div');metrics.className='metrics';for(const [label,value] of [['Findings on this page',result.findings.length],['Markets covered',(result.summary||[]).length],['Needs attention',(result.summary||[]).filter(r=>/unavailable|insufficient|partial/.test(r.status)).length]]){const card=node('div');card.append(node('span',label),node('strong',value));metrics.append(card);}content.append(metrics);
 if(source==='backtest')content.append(button('Configure & re-run backtests',configureBacktest));
 const tabs=node('div');tabs.className='mini-tabs';tabs.setAttribute('role','tablist');const panel=node('section');content.append(tabs,panel);
 function sortableHeader(label,key){
  if(source!=='backtest'||!key)return label;
  const active=backtestSort.key===key,b=button(label+(active?(backtestSort.order==='asc'?' ↑':' ↓'):' ↕'),()=>{
   backtestSort.order=active&&backtestSort.order==='asc'?'desc':'asc';backtestSort.key=key;page=0;
   findings(source).catch(e=>message(e.message,true));
  });b.className='sort-header';b.dataset.sortState=active?(backtestSort.order==='asc'?'ascending':'descending'):'none';
  b.title=key==='rating'?'Sort by your star rating (unrated last)':key==='evidence'?'Sort by direction, then stage':`Sort by ${label}`;return b;
 }
 const rows=result.findings.map(r=>{const s=r.signal;const detail=node('div');detail.append(node('strong',s.direction.toUpperCase()),node('p',s.stage_description||(s.signal_status==='provisional'?'Warm-up · potential divergence, awaiting the next candle.':'Confirmed · the following candle confirms the pivot.')),node('small',`${Number(s.price1.toPrecision(8))} → ${Number(s.price2.toPrecision(8))} · RSI ${s.rsi1.toFixed(2)} → ${s.rsi2.toFixed(2)} · outer BB slope ${Number.isFinite(s.band_slope_pct)?s.band_slope_pct.toFixed(2)+'%/candle':'not recorded'}`));if(r.archived)detail.append(node('small','Archived'));const actions=node('div');actions.append(button('Inspect candles',()=>openCandle(source,r.id)),button('Follow up',()=>{selectFinding(source,r.id);openFollowup(source,r);}));if(source==='live')actions.append(button(r.archived?'Restore':'Archive',()=>changeFinding(r,r.archived?'restore':'archive')),button('Delete',()=>changeFinding(r,'delete')));return[s.symbol,s.timeframe,detail,outcomeCell(r),displayTime(s.confirmed_at),actions,feedback(source,r)];});
 function show(which){panel.replaceChildren();for(const b of tabs.children)b.setAttribute('aria-selected',String(b.textContent===which));if(which==='Finding details'){const grid=table([['Asset','asset'],['Timeframe','timeframe'],['Divergence status','evidence'],['Observed gain / drawdown',null],['Signal time · Israel','confirmed_at'],['Actions',null],['Your review','rating']].map(([label,key])=>sortableHeader(label,key)),rows);for(const [index,tr] of [...grid.querySelectorAll('tr')].slice(1).entries()){tr.classList.add('finding-row');tr.dataset.findingId=result.findings[index].id;tr.classList.toggle('selected-row',selectedFindings[source]===tr.dataset.findingId);tr.setAttribute('aria-selected',String(selectedFindings[source]===tr.dataset.findingId));tr.tabIndex=0;tr.setAttribute('aria-label',`Inspect candles for ${result.findings[index].signal.symbol}`);tr.onclick=e=>{if(!e.target.closest('button,a,input,textarea,select,label'))openCandle(source,result.findings[index].id);};tr.onkeydown=e=>{if(e.target===tr&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openCandle(source,result.findings[index].id);}};}panel.append(grid);if(!rows.length)panel.append(node('p','No findings in this view yet. Check coverage for unavailable feeds.'));const pager=node('nav');pager.className='pagination';pager.setAttribute('aria-label','Backtest pages');
  const go=(target)=>{page=target;findings(source).catch(e=>message(e.message,true));};
  const pages=Math.max(result.page_count??(page+Number(result.has_more)),1);const addPage=(label,target,current=false,disabled=false)=>{const b=button(label,()=>go(target));b.disabled=disabled;if(current)b.setAttribute('aria-current','page');pager.append(b);};
  if(source==='backtest'){
   addPage('First',0,false,page===0);addPage('Previous',Math.max(0,page-1),false,page===0);
   let visible=pages<=7?Array.from({length:pages},(_,i)=>i):[...new Set([0,Math.max(0,page-1),page,Math.min(pages-1,page+1),pages-1])].sort((a,b)=>a-b),last=-1;
   for(const n of visible){if(n>last+1)pager.append(node('span','…'));addPage(String(n+1),n,n===page);last=n;}
   addPage('Next',Math.min(pages-1,page+1),false,page>=pages-1);addPage('Last',Math.max(0,pages-1),false,page>=pages-1);
   pager.append(node('small',`${result.total_count??0} findings · page ${page+1} of ${pages}`));
  }else{
   addPage('Previous',Math.max(0,page-1),false,page===0);pager.append(node('span',` Page ${page+1} `));addPage('Next',page+1,false,!result.has_more);
  }
  panel.append(pager);}else panel.append(table(['Asset','Timeframe','Status','Matches','Coverage details'],(result.summary||[]).map(r=>[r.asset,r.timeframe,r.status,r.signals??r.historical_matches??0,r.note||r.reason||r.data_notes||''])));}
 for(const label of ['Finding details','Coverage summary']){const b=button(label,()=>show(label));b.setAttribute('role','tab');tabs.append(b);}show('Finding details');
}
async function changeFinding(r,action){
 if(action==='delete'&&!confirm('Delete this signal from the workspace? It cannot be restored.'))return;
 try{await request('/api/finding-state',{source:'live',finding_id:r.id,action,revision:r.state_revision||0});await findings('live');message(action==='archive'?'Signal archived.':action==='restore'?'Signal restored.':'Signal deleted.');}catch(e){message(e.message,true);}
}
async function configureBacktest(){try{const options=await request('/api/backtests');const dialog=$('backtest-dialog'),form=$('backtest-form');form.replaceChildren(node('p',`Replay ${options.year} history with the selected data source. Missing combinations are reported as unavailable.`));
 const checks=(title,values)=>{const field=node('fieldset');field.append(node('legend',title));const selected=[];for(const value of values){const l=node('label',value),i=node('input');i.type='checkbox';i.value=value;i.checked=title!=='Timeframes'||value!=='1h';selected.push(i);l.prepend(i);field.append(l);}form.append(field);return()=>selected.filter(i=>i.checked).map(i=>i.value);};
 const assets=checks('Historical asset names',options.assets),timeframes=checks('Timeframes',options.timeframes);const strategy=node('select');strategy.setAttribute('aria-label','Strategy');for(const [key,text] of Object.entries(options.strategies)){const o=node('option',key==='confirmed'?'Confirmed RSI divergence':'Warm-up divergence');o.value=key;strategy.append(o);}const logic=node('p');logic.className='strategy-logic';strategy.onchange=()=>logic.textContent=options.strategies[strategy.value];strategy.onchange();form.append(node('label','Strategy'),strategy,logic);const source=node('select');source.setAttribute('aria-label','Historical data source');for(const key of options.sources||['csv']){const o=node('option',key==='alpaca'?'Alpaca US equities':key==='tiingo'?'Tiingo forex':'Stored CSV history');o.value=key;source.append(o);}form.append(node('label','Data source'),source);source.onchange=()=>{const allowed=source.value==='alpaca'?options.alpaca_assets:source.value==='tiingo'?options.tiingo_assets:(options.csv_assets||options.assets);for(const i of form.querySelectorAll('fieldset:first-of-type input')){i.disabled=!allowed.includes(i.value);i.checked=!i.disabled;}};source.onchange();if(options.sources?.includes('alpaca'))form.append(node('p','Alpaca supports US equities; Tiingo supports forex. Insufficient warmup is reported as partial history.'));const run=node('button','Run backtest');run.type='submit';form.append(run);form.onsubmit=async e=>{e.preventDefault();run.disabled=true;try{const job=await request('/api/backtests',{assets:assets(),timeframes:timeframes(),strategy:strategy.value,source:source.value});dialog.close();message('Backtest running…');watchBacktest(job.id);}catch(e){message(e.message,true);run.disabled=false;}};dialog.showModal();}catch(e){message(e.message,true);}}
async function watchBacktest(id){try{const value=await request('/api/backtests?job='+encodeURIComponent(id));if(value.job?.id===id&&['completed','failed'].includes(value.job.status)){message(value.job.error||'Backtest completed',value.job.status==='failed');page=0;await findings('backtest');}else setTimeout(()=>watchBacktest(id),2000);}catch(e){message(e.message,true);}}
async function loadLogs(){content.replaceChildren(node('h2','Activity & diagnostics'));const filter=node('select');for(const [value,label] of [['all','All events'],['errors','Errors / scans needing attention']]){const o=node('option',label);o.value=value;filter.append(o);}const search=node('input');search.placeholder='Search asset, event or failure reason';search.setAttribute('aria-label','Search logs');const order=node('select');for(const [value,label] of [['newest','Newest first'],['oldest','Oldest first'],['errors','Errors first']]){const o=node('option',label);o.value=value;order.append(o);}const panel=node('div');const refresh=button('Refresh logs',async()=>{refresh.disabled=true;try{rows=(await request('/api/logs?filter='+filter.value)).rows;render();message('Logs refreshed.');}catch(e){message(e.message,true);}finally{refresh.disabled=false;}});content.append(filter,search,order,refresh,panel);let rows=[];
 const failed=r=>/error|failed|unavailable|insufficient|retry/i.test(r.event+' '+r.details);
 function render(){const visible=rows.filter(r=>(filter.value==='all'||failed(r))&&(r.event+' '+r.details).toLowerCase().includes(search.value.toLowerCase())).sort((a,b)=>order.value==='errors'?(Number(failed(b))-Number(failed(a))||b.occurred-a.occurred):order.value==='oldest'?a.occurred-b.occurred:b.occurred-a.occurred);panel.replaceChildren(table(['Time · Israel','Event','Details'],visible.map(r=>{const time=node('div');time.append(node('strong',displayTime(r.occurred*1000)),node('small',`${Math.max(0,Math.floor((Date.now()/1000-r.occurred)/60))} min ago · Unix ${r.occurred}`));let details=r.details;try{const d=JSON.parse(details);details=`${d.asset||''} · ${d.timeframe||''} · ${d.status||''}. ${d.reason||d.data_notes||''} ${d.candles!==undefined?d.candles+' candles evaluated.':''}`;}catch{}return[time,r.event,details];})));}
 rows=(await request('/api/logs')).rows;filter.onchange=async()=>{try{rows=(await request('/api/logs?filter='+filter.value)).rows;render();}catch(e){message(e.message,true);}};order.onchange=render;search.oninput=render;render();}

function feedback(source,r){const wrap=node('div');wrap.className='feedback';let rating=r.feedback?.rating??null,revision=r.feedback?.revision||0,timer,saving=false,dirty=false;const stars=[],reviews=node('div');reviews.className='review-ratings';const userStars=node('div');userStars.className='user-stars';userStars.setAttribute('aria-label','Your quality rating');const comment=node('textarea');comment.maxLength=4000;comment.value=r.feedback?.comment||'';comment.placeholder='Comment';const progress=node('span');
 for(let i=1;i<=5;i++){const b=button(i<=rating?'★':'☆',()=>{rating=i;stars.forEach((s,k)=>s.textContent=k<i?'★':'☆');changed(0);});b.className='star';b.setAttribute('aria-label',`${i} stars`);stars.push(b);userStars.append(b);}const auto=node('span');auto.className='automatic-rating';r.ratingElement=auto;updateAutomaticRating(r);reviews.append(userStars,auto);wrap.append(reviews,comment,progress);
 function changed(delay){dirty=true;clearTimeout(timer);timer=setTimeout(save,delay);progress.textContent='Saving…';}
 async function save(){if(saving)return;saving=true;const submitted={rating,comment:comment.value};dirty=false;try{const value=await request('/api/feedback',{source,finding_id:r.id,revision,...submitted});revision=value.revision;progress.textContent=online?'Saved online':'Saved locally';}catch(e){dirty=true;progress.textContent=e.message;}finally{saving=false;if(dirty&&progress.textContent==='Saving…')timer=setTimeout(save,0);}}
 comment.oninput=()=>changed(600);comment.onblur=()=>{if(dirty&&!saving)save();};return wrap;
}
async function openCandle(source,id,target='pivot2'){selectFinding(source,id);try{const data=await request(`/api/candles?source=${source}&finding=${id}&target=${target}`);if(!$('candle-dialog').open)$('candle-dialog').showModal();$('candle-title').textContent=`${data.signal.symbol} · ${({monthly:'Monthly',weekly:'Weekly',daily:'Daily','4h':'4 hours','1h':'Hourly','60':'Hourly','240':'4 hours','D':'Daily','W':'Weekly','M':'Monthly'})[data.signal.timeframe]||data.signal.timeframe} candles${data.signal.direction?' · '+data.signal.direction.toUpperCase():''}`;const rules=data.signal.rules;$('candle-legend').textContent=`Bollinger Bands (${rules.bb_period}, ${rules.bb_multiplier}σ) · RSI (${rules.rsi_period}, Wilder).`; const slope=data.signal.band_slope_pct;if(Number.isFinite(slope)){const angle=Math.atan(slope/100)*180/Math.PI;$('candle-legend').textContent+=` ${data.signal.direction==='bullish'?'Lower':'Upper'} touching BB slope: ${slope>=0?'+':''}${slope.toFixed(3)}%/candle · normalized angle ${angle>=0?'+':''}${angle.toFixed(3)}° (${rules.band_slope_period||3} candles).`;}else $('candle-legend').textContent+=' Touching BB slope not recorded.'; $('candle-legend').title='Normalized angle = atan(slope % / 100), with one candle horizontally and a 100% price change vertically; independent of chart zoom. Indicators are recalculated from the displayed candles and may differ slightly from the values saved with the signal.'; $('candle-note').textContent='';if(online&&!data.tradingview_url){const settings=await request('/api/assets');const a=settings.config.assets.map(a=>{const p=a.timeframe_providers?.[data.signal.timeframe]||a.provider;return p==='kraken'?{...a,provider:p,exchange:'Kraken',tradingview_symbol:a.provider==='kraken'?a.tradingview_symbol:''}:p==='oanda'?{...a,provider:p,exchange:data.signal.symbol.split(':')[1],tradingview_symbol:a.provider==='oanda'?a.tradingview_symbol:''}:p==='tiingo'?{...a,provider:p,exchange:'Tiingo-UTC',tradingview_symbol:a.provider==='tiingo'?a.tradingview_symbol:''}:p==='alpaca'?{...a,provider:p,exchange:data.signal.symbol.split(':')[1],tradingview_symbol:a.provider==='alpaca'?a.tradingview_symbol:''}:a;}).find(a=>a.id===data.signal.symbol||`${a.provider}:${a.exchange||'configured'}:${a.symbol||a.id}`===data.signal.symbol);if(a?.tradingview_symbol){const interval={monthly:'M',weekly:'W',daily:'D','4h':'240','1h':'60'}[data.signal.timeframe];data.tradingview_url='https://www.tradingview.com/chart/?'+new URLSearchParams({symbol:a.tradingview_symbol,interval});}}const actions=$('candle-actions');actions.replaceChildren();for(const [key,label] of [['pivot1','First pivot'],['pivot2','Second pivot'],['confirmation',data.signal.signal_status==='provisional'?'Signal candle close':'Confirmation']])actions.append(button(label,()=>openCandle(source,id,key)));
 if(data.tradingview_url){const a=node('a','Open TradingView');a.href=data.tradingview_url;a.target='_blank';a.rel='noopener';a.title='Opens the configured comparison feed in TradingView.';actions.append(a);}
 const candles=data.candles;if(chart){chart.remove();chart=null;}$('chart').replaceChildren();$('candle-table').replaceChildren();
 if(candles.length){const library=await import('/web/chart.js');chart=await library.draw($('chart'),candles,data.signal,target);$('candle-table').replaceChildren(table(['Candle (Israel)','Open','High','Low','Close'],candles.filter(c=>c.start===data.signal.pivot1||c.start===data.signal.pivot2||c.end===data.signal.confirmed_at).map(c=>[displayTime(c.start),c.open,c.high,c.low,c.close])));}else{$('candle-note').textContent+=' No stored source candles are available for this finding.';}
 }catch(e){message(e.message,true);}}
$('close-backtest').onclick=()=>$('backtest-dialog').close();
$('close-chart').onclick=()=>$('candle-dialog').close();
$('candle-dialog').addEventListener('close',()=>{if(chart){chart.remove();chart=null;}if(location.pathname==='/candle'){const source=new URLSearchParams(location.search).get('source');location.assign(source==='backtest'?'/backtest':'/signals');}});
async function load(){if(online&&passwordSetupSession)return;if(online&&!token){$('login').hidden=false;return;}try{const path=location.pathname;$('connection').textContent=online?'Online database':'Local SQLite';if(path==='/assets')await loadAssets();else if(path==='/candle'){const p=new URLSearchParams(location.search);await openCandle(p.get('source'),p.get('finding'));}else if(path==='/backtest')await findings('backtest');else if(path==='/logs')await loadLogs();else if(path==='/signals'||path==='/dashboard')await findings('live');else await loadOverview();}catch(e){message(e.message,true);}}
load();

for(const a of document.querySelectorAll?.('nav a')||[])if(a.getAttribute('href')===location.pathname)a.setAttribute('aria-current','page');

async function loadOverview(){const data=await request('/api/findings?source=live&page=0');content.replaceChildren(node('h2','Market monitor'),node('p','Closed-candle divergence research · live scanner and alert delivery'));const actions=node('div');actions.append(button('Review signals',()=>location.assign('/signals')),button('Configure backtest',configureBacktest),button('Catch up',requestCatchup));const whitepaper=node('a','Strategy white paper');whitepaper.href='https://docs.google.com/document/d/1UbzPu5QlFio5KPctVnYKV-VTwCsi2Q4kXsCicfLCTCA/edit?usp=sharing';whitepaper.target='_blank';whitepaper.rel='noopener';actions.append(whitepaper);const download=node('a','Download Windows app');download.href='https://github.com/idodidodi/trading-bot/releases/latest/download/FamilyTradingBot.exe';actions.append(download);content.append(actions);if(!online)loadUpdateControls(actions);const scan=data.scan;if(scan){content.append(node('p',`Last cycle: ${displayTime(scan.scanned_at)} · ${scan.phase||'scanned'}. ${scan.next_scan_at?'Next scan: '+displayTime(scan.next_scan_at):'Awaiting scanner schedule.'}`));}else content.append(node('p','Online coverage reflects the latest successful local sync.'));const coverage=data.summary||[];const failures=coverage.filter(r=>/unavailable|insufficient/.test(r.status));if(failures.length){const warning=node('p',`${failures.length} asset/timeframe combinations could not be scanned. See coverage below and Logs for reasons.`);warning.className='error';content.append(warning);}content.append(table(['Asset','Timeframe','Coverage','Latest closed candle · Israel','Details'],coverage.map(r=>[r.asset,r.timeframe,r.status,r.last_closed_at?displayTime(r.last_closed_at):'Unavailable',r.reason||r.data_notes||(r.limited_history?'Limited history':'')])));}

function updateAutomaticRating(r){if(!r.ratingElement)return;const f=r.followup;r.ratingElement.textContent=f?.rating?`Auto: ${f.rating} / 5${f.mode==='all'?' · all history':''}${f.status==='ongoing'?' · ongoing':''}`:'Auto: awaiting follow-up';r.ratingElement.title=`Based on maximum directional gain divided by maximum drawdown. Window: ${f?.mode==='all'?'all available history':'through first recovery'}.`;}
const elapsedMinutes=ms=>{if(ms==null)return '—';const minutes=Math.round(ms/60000);return `${Math.floor(minutes/60)}:${String(minutes%60).padStart(2,'0')}`;};
async function openFollowup(source,r,mode='recovery'){
 const dialog=$('followup-dialog'),panel=$('followup-content');if(!dialog.open)dialog.showModal();$('followup-title').textContent=`${r.signal.symbol} · ${r.signal.timeframe} follow-up`;panel.replaceChildren(node('p','Calculating follow-up…'));
 const requestId=(dialog.dataset.requestId=String(Number(dialog.dataset.requestId||0)+1));
 try{const data=await request(`/api/followup?source=${source}&finding=${r.id}&mode=${mode}`);if(dialog.dataset.requestId!==requestId)return;const f=data.followup;r.followup=f;updateAutomaticRating(r);updateOutcome(r);panel.replaceChildren();
 const select=node('select');select.setAttribute('aria-label','Follow-up window');for(const [value,label] of [['recovery','Through first recovery'],['all','All available history']]){const o=node('option',label);o.value=value;select.append(o);}select.value=mode;select.onchange=()=>openFollowup(source,r,select.value);panel.append(select);
 panel.append(node('p',`From second divergence pivot: ${displayTime(f.baseline_at)} · price ${Number(f.baseline_price.toPrecision(8))}. ${r.signal.direction==='bullish'?'Bullish: upward moves count as gain.':'Bearish: downward moves count as gain.'}`));
 if(f.status==='unavailable'){panel.append(node('p',f.reason));return;}
 panel.append(table(['Outcome','Maximum move','Price level','Time from divergence · hours:minutes'],[
 ['Drawdown',`${f.drawdown_pct.toFixed(2)}%`,f.drawdown_price==null?'—':Number(f.drawdown_price.toPrecision(8)),elapsedMinutes(f.drawdown_elapsed_ms)],
 ['Gain',`${f.gain_pct.toFixed(2)}%`,f.gain_price==null?'—':Number(f.gain_price.toPrecision(8)),elapsedMinutes(f.gain_elapsed_ms)],
 [mode==='all'?'Recovery after worst drawdown':'First recovery',f.recovery_at?'Returned to baseline':f.status==='no drawdown'?'No adverse move':'Not recovered yet',f.recovery_at?displayTime(f.recovery_at):'—',elapsedMinutes(f.recovery_elapsed_ms)]
 ]));
 panel.append(node('p',`Automatic rating: ${f.rating} / 5 · Gain / drawdown: ${f.gain_drawdown_ratio==null?(f.gain_pct?'No drawdown':'—'):f.gain_drawdown_ratio.toFixed(2)} · ${f.candles} closed candles through ${displayTime(f.through_at)}.`));
 panel.append(node('p','Rating: 5 for gain/drawdown ≥ 3 (or gain with no drawdown), 4 for ≥ 2, 3 for ≥ 1, 2 for ≥ 0.5, otherwise 1. Zero gain scores 1. The rating reflects observed history and may change as more candles close.'));
 panel.append(node('small','Elapsed times use hours:minutes, rounded to whole minutes from the pivot candle start to the close of the candle containing the extreme. The pivot candle is excluded because its wick order is unknown. Recovery requires a later candle closing at or beyond the baseline after an adverse wick. The full recovery candle is included; intrabar ordering is unknown. Missing stored candles can limit these results.'));
 }catch(e){if(dialog.dataset.requestId===requestId)panel.replaceChildren(node('p',e.message));}
}
$('close-followup').onclick=()=>$('followup-dialog').close();

async function requestCatchup(){try{const result=await request('/api/catchup',{action:'request'});message(result.status==='pending'?'Catch-up queued. The scanner will process missed closed candles and send a Telegram summary when online.':`Catch-up ${result.status}${result.reason?': '+result.reason:''}`);watchCatchup(result.id);}catch(e){message(e.message,true);}}
async function loadUpdateControls(actions){try{const value=await request('/api/updates');if(!value.supported)return;const label=node('span',`Windows app ${value.version} · hourly updates enabled`);actions.append(label,button('Check for updates',async()=>{try{const result=await request('/api/updates',{action:'check'});message(result.message||'Checking for updates…');}catch(e){message(e.message,true);}}));}catch{}}

async function watchCatchup(id,attempt=0){if(attempt>60)return;setTimeout(async()=>{try{const value=await request('/api/catchup');if(value.id!==id)return;if(value.status==='completed'||value.status==='failed')message(`Catch-up ${value.status}: ${value.findings||0} new findings, ${value.unavailable||0} unavailable histories. ${value.reason||''}`,value.status==='failed');else watchCatchup(id,attempt+1);}catch{}},10000);}

async function momentumFindings(source){
 content.replaceChildren(node('h2','Loading momentum…'),strategySelector(source));
 const data=await request('/api/momentum?source='+source);if(strategyViews[source]!=='momentum')return;
 content.replaceChildren(node('h2',source==='live'?'Daily momentum signals':'Momentum backtests'),strategySelector(source));
 content.append(node('p',data.note||''));
 const latest=data.latest;
 if(source==='live'&&latest){
  content.append(node('p',`Scan: ${displayTime(latest.scanned_at)} · ${latest.status} · ${latest.version}`));
  content.append(table(['Market','Daily result','Qualified candidates'],(latest.results||[]).map(r=>[r.market,r.status,r.candidates])));
  if(Date.now()-latest.scanned_at>36*3600000)content.append(node('p','Scan is stale. Check the local worker and cloud sync.'));
 }
 if(source==='backtest'){
  const m=data.metrics||{};
  content.append(node('p',`${m.candidates??0} candidates · ${m.closed_trades??0} closed trades · win rate ${m.win_rate_pct==null?'—':m.win_rate_pct.toFixed(1)+'%'} · average net return ${m.average_net_pct==null?'—':m.average_net_pct.toFixed(2)+'%'}`));
  if(data.generated_at)content.append(node('p','Last replay: '+displayTime(data.generated_at)));
  content.append(node('p','Momentum backtests refresh from daily scan history. The RSI replay controls apply to the RSI view.'));
 }
 const signals=data.signals||[],market=node('select');market.setAttribute('aria-label','Momentum market');
 for(const [key,name] of [['all','Stocks and crypto'],['stock','US stocks'],['crypto','Crypto']]){const o=node('option',name);o.value=key;market.append(o);}
 const panel=node('section');content.append(market,panel);
 const price=v=>Number(v.toPrecision(7));
 function render(){panel.replaceChildren(table(['Market / asset','Direction / confirmation','Entry range','Stop / target','Evidence','Outcome'],signals.filter(s=>market.value==='all'||s.market===market.value).map(s=>{
  const f=s.outcome||{},out=node('div');out.append(node('strong',f.status||'Awaiting evaluation'));if(f.net_pct!=null)out.append(node('p',`Net ${f.net_pct.toFixed(2)}%`));
  const entry=node('div');entry.append(node('strong',`${price(s.entry_min)} – ${price(s.entry_max)}`),node('small','Next session open only; skip outside range or below 1.5 reward/risk.'));if(s.entry_open_at)entry.append(node('small','Entry session: '+displayTime(s.entry_open_at)+' · expires '+displayTime(s.expires_at)));
  return [s.market+' · '+s.symbol,s.direction.toUpperCase()+' · '+displayTime(s.confirmed_at),entry,`${price(s.stop)} / ${price(s.target)}`,`ROC ${s.roc_pct.toFixed(2)}% · efficiency ${s.efficiency.toFixed(2)} · extension ${s.extension_atr.toFixed(2)} ATR · ${s.version}`,out];
 })));if(!signals.length)panel.append(node('p','No momentum signals available. Review the daily result and coverage.'));}
 market.onchange=render;render();
 if(source==='live'&&latest){const details=node('details');details.append(node('summary','Momentum scan coverage'),table(['Market','Asset','Status','Details'],latest.coverage.map(r=>[r.market,r.symbol||'Broad universe',r.status,r.reason||(r.eligible!=null?`${r.eligible} eligible histories`:r.candles?`${r.candles} closed daily candles`:'')])));content.append(details);}
}
